name = "tobulaelektra-oauth"
main = "worker.js"
compatibility_date = "2026-04-02"
workers_dev = false

[vars]
REDIRECT_URI = "https://oauth.tobulaelektra.lt/callback"

[[routes]]
pattern = "oauth.tobulaelektra.lt"
custom_domain = true
