backend:
  name: github
  repo: ElaineAres/elektrikas-marius-klaipeda
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "site"
    label: "Site"
    files:
      - file: "content/site.json"
        label: "Main content"
        name: "main"
        fields:
          - { label: "Pavadinimas", name: "title", widget: "string" }
          - { label: "Hero title", name: "hero_title", widget: "string" }
          - { label: "Hero text", name: "hero_text", widget: "text" }
          - { label: "Telefonas", name: "phone", widget: "string" }
