backend:
  name: github
  repo: ElaineAres/elektrikas-marius-klaipeda
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

locale: "lt"

collections:
  - name: "pages"
    label: "Puslapiai"
    files:
      - file: "index.html"
        label: "Pagrindinis"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
